apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mixh56188-go 
  janus-idp.io/tekton: mixh56188-go
  backstage.io/kubernetes-id: mixh56188-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mixh56188-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml