apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mixh56188-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mixh56188-go 
  name: mixh56188-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mixh56188-go 
